### ISSUE TITLE
Tried to upgrade this to the most recent reby_webgl2, failure

### ISSUE THREAD

**Issue by Zageron** [mrk-its/bevy_webgl2_app_template#2]
```toml

[features]
default = ["bevy/bevy_gltf", "bevy/bevy_winit", "bevy/render", "bevy/png"]

native = ["bevy/bevy_wgpu"]

web = ["bevy_webgl2"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "1398d7833007e85198cfd35d5fabc70b51b4db31", default-features = false }
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2", optional = true }
winit = "0.23.0"

[profile.dev]
opt-level = 's'

[profile.release]
lto = true
opt-level = 's'

```

This is what I have that functions. Using the defaults in this project fail for me.
Are you on nightly or on stable, what configuration etc..., for the bevy_webgl2 repository to work as a dependency?

Thanks!
