### ISSUE TITLE
Replace native/web features with platform-specific dependencies once Rust 1.51.0 releases

### ISSUE THREAD

**Issue by daboross** [mrk-its/bevy_webgl2_app_template#5]
With the new feature resolver stabilizing in 1.51.0, we should be able to get rid of `native` and `web` features, and instead use something like:

```toml
[target.'cfg(target_arch = "wasm32)'.dependencies]
bevy = {version = "0.4.0", default-features=false}
bevy_webgl2 = {version="0.4.0", optional=true}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = {version="0.4.0", default-features=false, features = ["bevy_wgpu"]}
```

I'd like to submit a PR for this, but it won't work until the `itarget` feature part of [RFC 2957](https://github.com/rust-lang/rfcs/blob/master/text/2957-cargo-features2.md) is stabilized, which as of https://github.com/rust-lang/cargo/pull/8997 will be Rust 1.51.0.
